#!/bin/bash
set -eu

function log {
    printf "\e[1;34m[build]\e[0m\e[1;94m ${1}\e[0m\n"
}

TARGET="docs"

rm -rf ${TARGET}
rm -rf build-generated
mkdir -p ${TARGET}
mkdir -p build-generated

source cmd/config
echo "window.allocator = window.allocator || {}; window.allocator.meta=${META}" > "build-generated/GENERATED-meta.js"
echo "meta=${META}" > "${TARGET}/meta.js"

log "Compiling project..."
npx elm make elm-allocator/src/Allocator.elm        --output=build-generated/GENERATED-allocator.js     --optimize > /dev/null

log "Minifing JavaScript files..."
node cmd/minify.js "Allocator" ${VERSION} "Commit ${COMMIT} - Built ${BUILD_TIMESTAMP_ISO}" "GENERATED-allocator.js" "allocator-starter.js" "MINIFIED-allocator.js"

log "Copying files..."
cp build-generated/MINIFIED-allocator.js ${TARGET}/allocator.min.js
cp build-generated/MINIFIED-allocator.js ${TARGET}/allocator.${VERSION}.min.js
cp public/index.html                     ${TARGET}/index.html
cp public/frozen-versions/*              ${TARGET} | true

log "Files available in the 'build' folder:"
printf "\n\e[1;34m"
ls -lR ${TARGET}
printf "\n"
