#!/bin/bash
set -eu

source cmd/config
echo "window.allocation = window.allocation || {}; window.allocation.meta=${META}" > "build-generated/GENERATED-meta.js"
npx concurrently --kill-others --prefixColors=auto \
    "npx elm-watch@2.0.0-beta.6 hot allocation"
