#!/bin/bash
set -eu

source cmd/config
mkdir -p build-generated
echo "window.allocator = window.allocator || {}; window.allocator.meta=${META}" \
    > "build-generated/GENERATED-meta.js"
npx elm-watch@2.0.0-beta.6 hot allocator | cat
